<div class="par">
  <form action="/acc" method="post">
    <fieldset class="inline">
      <label>Add funds:</label>
      <select>
        <option>$5.00</option>
        <option>$25.00</option>
        <option>$100.00</option>
      </select>
      <button type="submit"><i class="fa fa-cc-paypal"></i></button>
      <button type="submit"><i class="fa fa-cc-stripe"></i></button>
    </fieldset>
  </form>
</div>
<div class="par">
  Period:
  <strong>all time</strong>
  | <a href="">this month</a>
  | <a href="">this week</a>
</div>
<div class="par">
  Group by:
  <strong>nothing</strong>
  | <a href="">entity</a>
  | <a href="">slot</a>
</div>
<div class="par">
  Sort by:
  <strong>date</strong>
  | <a href="">amount</a>
</div>
<div class="par">
  Start balance: $90.87
</div>
<div class="par">
  <table>
    <tbody>
      <tr>
        <td>2014-03-01T03:05:34Z</td>
        <td><a href="/">#48372/person</a></td>
        <td><a href="/slot">#6579534/email</a></td>
        <td style="text-align:right"><span style="color:green">$0.03</span></td>
      </tr>
      <tr>
        <td>2014-10-01T09:35:29Z</td>
        <td><a href="/">#998647/person</a></td>
        <td><a href="/slot">#65122334/works-for</a></td>
        <td style="text-align:right"><span style="color:red">-$0.15</span></td>
      </tr>
      <tr>
        <td>2014-10-17T09:22:29Z</td>
        <td><a href="/">#998647/person</a></td>
        <td><a href="/slot">#651804/address</a></td>
        <td style="text-align:right"><span style="color:green">$7.50</span></td>
      </tr>
      <tr>
        <td><a href="/trn">2014-10-19T19:11:29Z</a></td>
        <td colspan="2">funded by PayPal #AA-8467366573TT</td>
        <td style="text-align:right"><span style="color:green">$25.00</span></td>
      </tr>
      <tr>
        <td><a href="/trn">2014-10-29T18:32:37Z</a></td>
        <td colspan="2">withdrawal request for $55.00</td>
        <td style="text-align:right"><span style="color:gray">pending</span></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="par">
  End balance: $87.13
</div>
<div class="par">
  <a href="">Download in CSV</a>
</div>
