<div class="par">
  #65399/person
  <a href="request">request</a>
</div>
<ul class="slots par">
  <li>
    <div>name <a href="add">add</a></div>
    <ul>
      <li><a href="/slot">*</a> Yegor Bugayenko</li>
    </ul>
  </li>
  <li>
    <div>works-for <a href="add">add</a></div>
    <ul>
      <li><a href="/slot">*</a> <a href="">TechnoPark Corp.</a> since 2001</li>
    </ul>
  </li>
  <li>
    <div>email <a href="add">add</a></div>
    <ul>
      <li>
        <a href="/slot">*</a>
        <span>yegor@tpc2.com</span>
        <a href="">&#162;5</a>
      </li>
      <li>
        <a href="/slot">*</a>
        <span>yegor@teamed.io</span>
        &#162;8
        <a href="/dispute">dispute</a>
      </li>
      <li>
        *
        <a href="">&#162;2</a>
        (1 refund)
      </li>
    </ul>
  </li>
  <li>
    <div>address <a href="add">add</a></div>
    <ul>
      <li>
        *
        <a href="">$5.00</a>
      </li>
      <li>
        ?
        $7.50
        <a href="/add">add and earn</a>
      </li>
    </ul>
  </li>
  <li>
    <div>biography <a href="add">add</a></div>
    <ul>
      <li>
        <a href="/slot">*</a>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat.
      </li>
    </ul>
  </li>
</ul>
