<div class="par">
  #65399/person
  <a href=""><i class="fa fa-rss"></i></a>
  <a href="">request</a>
</div>
<ul class="slots par">
  <li>
    <div>name <a href=""><i class="fa fa-plus-square-o"></i></a></div>
    <ul>
      <li><a href=""><i class="fa fa-paperclip"></i></a> Yegor Bugayenko</li>
    </ul>
  </li>
  <li>
    <div>works-for <a href=""><i class="fa fa-plus-square-o"></i></a></div>
    <ul>
      <li><a href=""><i class="fa fa-paperclip"></i></a> <a href="">TechnoPark Corp.</a> since 2001</li>
    </ul>
  </li>
  <li>
    <div>email <a href=""><i class="fa fa-plus-square-o"></i></a></div>
    <ul>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        <span>yegor@tpc2.com</span>
        <span class="source">&#162;5<a href=""><i class="fa fa-close"></i></a></span>
      </li>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        <span>yegor@teamed.io</span>
        <span class="source">&#162;8<a href=""><i class="fa fa-close"></i></a></span>
      </li>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        <a href="">&#162;2</a>
        <span class="rate">1<i class="fa fa-warning"></i></span>
      </li>
    </ul>
  </li>
  <li>
    <div>address <a href=""><i class="fa fa-plus-square-o"></i></a></div>
    <ul>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        <a href="">$5.00</a>
      </li>
    </ul>
  </li>
  <li>
    <div>biography <a href=""><i class="fa fa-plus-square-o"></i></a></div>
    <ul>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        <a href="">2300 words</a>
      </li>
      <li>
        <a href=""><i class="fa fa-paperclip"></i></a>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat.
      </li>
    </ul>
  </li>
</ul>
