<div class="par">
  435 entities found (page 1/23):
</div>
<div class="par">
  <div><a href="/entity">#65399/person</a> 16 slots</div>
  <div>name: "Yegor Bugayenko"</div>
  <div>works-for: "TechnoPark Corp. since 2001"</div>
  <div>email: "yegor@tpc2.com"</div>
</div>
<div class="par">
  <div><a href="/entity">#8977986/person</a> 7 slots</div>
  <div>name: "Steve Jobs"</div>
  <div>works-for: "Apple Inc. (Cupertino, CA) since 1976"</div>
  <div>email: "steve@apple.com"</div>
  <div>date-of-birth: February 24, 1955</div>
</div>
<div class="par">
  <a href="">more</a>
</div>
