<div class="par">
  #65399/person
</div>
<div class="par">
  <form action="/entity" method="post">
    <fieldset>
      <label>Exclusive royal-free?</label>
      <input type="checkbox" name="price"/>
      <label>How much you are ready to pay, in USD?</label>
      <input name="price" size="5" placeholder="0.00"/>
      <label>What do you want to know?</label>
      <select>
        <option>works-for</option>
        <option>address</option>
        <option>mobile-phone</option>
      </select>
      <label>Any specific requests?</label>
      <textarea name="text"></textarea>
      <button type="submit">Add</button>
    </fieldset>
  </form>
</div>
