<div class="par">
  #65399/person #9889472/email
</div>
<div class="par">
  <form action="/slot" method="post">
    <fieldset>
      <label>Make changes, if necessary:</label>
      <textarea name="text">yegor@teamed.io</textarea>
      <button type="submit">Modify</button>
    </fieldset>
  </form>
</div>
<ul class="slots par">
  <li>
    <div>2014-11-01T03:05:34Z price set to $1.15</div>
  </li>
  <li>
    <div>2014-10-23T19:04:24Z modified</div>
    <div>yegor@teamed.io</div>
  </li>
  <li>
    <div>2014-10-23T18:56:03Z added</div>
    <div>yegor@teamed..io</div>
  </li>
</ul>
