<div class="par">
  <strong>submit new entity</strong>
</div>
<div class="par">
  <form action="/" method="post">
    <fieldset>
      <label>Entity type:</label>
      <select>
        <option>person</option>
        <option>company</option>
        <option>web-domain</option>
      </select>
      <label>Mandatory slots:</label>
      <textarea name="text"></textarea>
      <button type="submit">Submit</button>
    </fieldset>
  </form>
</div>
